services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - nodered

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
